language: node_js

node_js:
- 10.4.1

services:
- postgresql

before_script:
- psql -c 'create database escapeAR_dev;' -U postgres

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - secure: rm3xbJO3LGansaIcz5k3xhEf1wSWyJYkZ5D1pTM23rbZQtjr88XAMHUK0w47L4TIWCOMmqA3zccqQlqQC6c5NgjLV1l3wGovTeyrRHBb0wkO/7A4IVMESTDuUIYDcR+fQdBv8f19Dr0OtFqZo7dKYqPou0f5+pAsWRlQjXr/diMm3IDOCIVjA8efOoc4XmIy65f0dKYfNGI6N60yH8yFH47OqSOeJYJuTx7DskJOKcO1UQ4kKrqTPeAdYZf6UtSzxkqvS0jXhCbXKkeUB4ncK32fLH3Xt8skH7CpOEwMPtakCpS4BHOefMWYX8sepqAJrk/2HTCrCeggjZzKVdjrTWmZ1BUilUdlMBdCyPrDbqMMs/Uj20jmjDrJUMB/D5kU7teR250W2QaFRC7Jo4nb3hg0ytGD9K5F0goi27skCSgMc5EUHzOgSs40rCzrxT+5MuM0nNB/snmqxRyx0KZlRjAdIuOEFc9VO1YnZrZg8GIH9kdy3Co9WJfPHkBhC0xjlKXyJqfnWua97TLCVX20J4HcymBMiGsgiN8VyJRM8sS2GzXAunDlKnsLM6bL3njsvIwwGjX/o8AWTi4WhnZUm1mUni7b7++t+AQqOpK3HwCA0oybMsQ5S5lyYYrMov1QAJb8J8sBfuL0yRm+s7XgEV8VIsVfsMSCks3iGVHe4C4=
